In [ ]:
from collections import Counter
import json
import os
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# ==============================================================================
# 0. MAPPER: ΦΟΡΤΩΣΗ ESCO OCCUPATIONS ΓΙΑ ΜΕΤΑΤΡΟΠΗ URIS ΣΕ ΟΝΟΜΑΤΑ
# ==============================================================================
esco_occ_map = {}
if os.path.exists("occupations_en.csv"):
    df_esco_occ = pd.read_csv("occupations_en.csv")
    # Δημιουργία λεξικού: conceptUri -> preferredLabel
    esco_occ_map = dict(
        zip(df_esco_occ["conceptUri"], df_esco_occ["preferredLabel"])
    )
    print(f"✅ Φορτώθηκαν {len(esco_occ_map)} αντιστοιχίσεις επαγγελμάτων ESCO.")


def get_occ_name(uri):
    """Επιστρέφει το όνομα του επαγγέλματος αν υπάρχει στο ESCO, αλλιώς το URI/ISCO"""
    if uri in esco_occ_map:
        return esco_occ_map[uri]
    # Αν είναι ISCO code (π.χ. C2433)
    if "isco" in uri:
        return f"ISCO Group: {uri.split('/')[-1]}"
    return uri.split("/")[-1]  # Επιστρέφει το ID


def get_skill_name(uri):
    """Καθαρίζει το Skill URI για καλύτερη εμφάνιση"""
    return uri.split("/")[-1][:8] + "..." if "/" in uri else uri


# ==============================================================================
# 1. ΦΟΡΤΩΣΗ ΚΑΙ ΤΩΝ 36 DATASETS (ME SAFETY CHECKS)
# ==============================================================================
BASE_DIR = "."  # /content στο Colab

COUNTRIES = [
    "czechia",
    "france",
    "germany",
    "greece",
    "italy",
    "poland",
    "romania",
    "spain",
    "sweden",
]
CATEGORIES = ["green", "lignite"]
KINDS = ["jobs", "profiles"]


def load_records_safe(path):
    """Loader με έλεγχο τύπων για αποφυγή AttributeError"""
    if not os.path.exists(path):
        # Δοκιμή με ή χωρίς .json επέκταση
        if os.path.exists(f"{path}.json"):
            path = f"{path}.json"
        else:
            return []

    with open(path, "r", encoding="utf-8") as f:
        content = f.read()

    try:
        data_ = json.loads(content)
        if isinstance(data_, list):
            return [x for x in data_ if isinstance(x, dict)]
        elif isinstance(data_, dict):
            for v in data_.values():
                if isinstance(v, list):
                    return [x for x in v if isinstance(x, dict)]
            return [data_]
    except json.JSONDecodeError:
        pass

    records = []
    for line in content.splitlines():
        line = line.strip().rstrip(",")
        if not line or line in ("[", "]", "{", "}"):
            continue
        try:
            item = json.loads(line)
            if isinstance(item, dict):
                records.append(item)
        except json.JSONDecodeError:
            continue
    return records


# Φόρτωση
data = {"jobs": {"green": {}, "lignite": {}}, "profiles": {"green": {}, "lignite": {}}}

for kind in KINDS:
    for category in CATEGORIES:
        for country in COUNTRIES:
            p = f"{BASE_DIR}/{kind}_{country}_{category}_clean.json"
            data[kind][category][country] = load_records_safe(p)

print("✅ Η ασφαλής φόρτωση των 36 datasets ολοκληρώθηκε!\n")

# ==============================================================================
# 2. TOP-5 ZΗΤΟΥΜΕΝΕΣ ΔΕΞΙΟΤΗΤΕΣ (JOBS) ΑΝΑ ΧΩΡΑ
# ==============================================================================
print("=" * 80)
print(" 1. TOP-5 ZΗΤΟΥΜΕΝΕΣ ΔΕΞΙΟΤΗΤΕΣ (SKILLS) ΑΝΑ ΧΩΡΑ (JOBS) ")
print("=" * 80)

for country in COUNTRIES:
    print(f"\n📍 ΧΩΡΑ: {country.upper()}")
    for cat in CATEGORIES:
        jobs = data["jobs"][cat].get(country, [])
        skills_list = [
            s
            for j in jobs
            if isinstance(j, dict)
            for s in j.get("skills", [])
            if s
        ]
        top_skills = Counter(skills_list).most_common(5)

        print(f"  ► [{cat.upper()} JOBS] (Σύνολο Αναφορών: {len(skills_list)})")
        if not top_skills:
            print("     Δεν βρέθηκαν skills.")
        for sk_uri, count in top_skills:
            print(f"     • {get_skill_name(sk_uri)} ({sk_uri}): {count} αναφορές")

# ==============================================================================
# 3. TOP-5 ΔΕΞΙΟΤΗΤΕΣ ΕΡΓΑΖΟΜΕΝΩΝ (PROFILES) ΑΝΑ ΧΩΡΑ
# ==============================================================================
print("\n" + "=" * 80)
print(" 2. TOP-5 ΔΕΞΙΟΤΗΤΕΣ ΕΡΓΑΖΟΜΕΝΩΝ ΑΝΑ ΧΩΡΑ (PROFILES) ")
print("=" * 80)

for country in COUNTRIES:
    print(f"\n📍 ΧΩΡΑ: {country.upper()}")
    for cat in CATEGORIES:
        profiles = data["profiles"][cat].get(country, [])
        skills_list = [
            s
            for prof in profiles
            if isinstance(prof, dict)
            for s in prof.get("skills", [])
            if s
        ]
        top_skills = Counter(skills_list).most_common(5)

        print(
            f"  ► [{cat.upper()} PROFILES] (Σύνολο Αναφορών: {len(skills_list)})"
        )
        if not top_skills:
            print("     Δεν βρέθηκαν skills.")
        for sk_uri, count in top_skills:
            print(f"     • {get_skill_name(sk_uri)} ({sk_uri}): {count} αναφορές")

# ==============================================================================
# 4. TOP-5 OCCUPATIONS ΣΤΙΣ ΑΓΓΕΛΙΕΣ (JOBS) ME ΑΝΤΙΣΤΟΙΧΙΣΗ ΟΝΟΜΑΤΩΝ ESCO
# ==============================================================================
print("\n" + "=" * 80)
print(" 3. TOP-5 ΠΙΟ ΣΥΧΝΑ ΕΠΑΓΓΕΛΜΑΤΑ (ESCO OCCUPATIONS) ΣΤΙΣ ΑΓΓΕΛΙΕΣ (JOBS) ")
print("=" * 80)

for country in COUNTRIES:
    print(f"\n📍 ΧΩΡΑ: {country.upper()}")
    for cat in CATEGORIES:
        jobs = data["jobs"][cat].get(country, [])
        occs_list = [
            o
            for j in jobs
            if isinstance(j, dict)
            for o in j.get("occupations", [])
            if o
        ]
        top_occs = Counter(occs_list).most_common(5)

        print(f"  ► [{cat.upper()} JOBS]")
        if not top_occs:
            print("     Δεν βρέθηκαν occupations.")
        for occ_uri, count in top_occs:
            occ_name = get_occ_name(occ_uri)
            print(f"     • {occ_name}: {count} αγγελίες")

# ==============================================================================
# 5. ΣΥΓΚΡΙΤΙΚΗ ΑΝΑΛΥΣΗ: GREEN VS LIGNITE JOBS & COMMON SKILLS
# ==============================================================================
print("\n" + "=" * 80)
print(" 4. ΣΥΓΚΡΙΤΙΚΗ ΑΝΑΛΥΣΗ: GREEN VS LIGNITE JOBS & ΚΟΙΝΕΣ ΔΕΞΙΟΤΗΤΕΣ ")
print("=" * 80)

transition_stats = []

for country in COUNTRIES:
    n_green = len(data["jobs"]["green"].get(country, []))
    n_lignite = len(data["jobs"]["lignite"].get(country, []))
    ratio = round(n_green / n_lignite, 2) if n_lignite > 0 else np.nan

    green_skills = set(
        s
        for j in data["jobs"]["green"].get(country, [])
        if isinstance(j, dict)
        for s in j.get("skills", [])
        if s
    )
    lignite_skills = set(
        s
        for j in data["jobs"]["lignite"].get(country, [])
        if isinstance(j, dict)
        for s in j.get("skills", [])
        if s
    )
    common_skills = green_skills.intersection(lignite_skills)

    transition_stats.append(
        {
            "Country": country.capitalize(),
            "Green Jobs": n_green,
            "Lignite Jobs": n_lignite,
            "Green/Lignite Ratio": ratio,
            "Common Skills": len(common_skills),
        }
    )

df_trans = pd.DataFrame(transition_stats)
display(df_trans)

# ==============================================================================
# 6. SKILL MATCHING SCORE & GAP ANALYSIS (PROFILES VS JOBS)
# ==============================================================================
print("\n" + "=" * 80)
print(" 5. SKILL MATCHING SCORE & GAP ANALYSIS (LIGNITE PROFILES VS GREEN JOBS) ")
print("=" * 80)

match_results = []

for country in COUNTRIES:
    lignite_prof_skills = set(
        s
        for p in data["profiles"]["lignite"].get(country, [])
        if isinstance(p, dict)
        for s in p.get("skills", [])
        if s
    )

    green_job_skills_counter = Counter(
        [
            s
            for j in data["jobs"]["green"].get(country, [])
            if isinstance(j, dict)
            for s in j.get("skills", [])
            if s
        ]
    )
    green_job_skills_set = set(green_job_skills_counter.keys())

    if len(lignite_prof_skills) > 0:
        matched = lignite_prof_skills.intersection(green_job_skills_set)
        score = round((len(matched) / len(lignite_prof_skills)) * 100, 2)
    else:
        score = 0.0

    match_results.append(
        {
            "Country": country.capitalize(),
            "Lignite Profile Skills": len(lignite_prof_skills),
            "Green Job Skills Needed": len(green_job_skills_set),
            "Skill Matching Score (%)": score,
        }
    )

df_match = pd.DataFrame(match_results)
display(df_match)

✅ Η ασφαλής φόρτωση των 36 datasets ολοκληρώθηκε!

================================================================================
 1. TOP-5 ZΗΤΟΥΜΕΝΕΣ ΔΕΞΙΟΤΗΤΕΣ (SKILLS) ΑΝΑ ΧΩΡΑ (JOBS)
================================================================================

📍 ΧΩΡΑ: CZECHIA
  ► [GREEN JOBS] (Σύνολο Αναφορών: 1291)
     • 199f7919... (http://data.europa.eu/esco/skill/199f7919-5114-41b6-b6a5-41e0e4896ec1): 47 αναφορές
     • 3de6d427... (http://data.europa.eu/esco/skill/3de6d427-546b-450b-97ba-d3d50eb274da): 36 αναφορές
     • 5b06c369... (http://data.europa.eu/esco/skill/5b06c369-10db-477d-a8df-987179324001): 28 αναφορές
     • f806d624... (http://data.europa.eu/esco/skill/f806d624-7700-4e47-9f7b-253d4d6ab9e5): 24 αναφορές
     • db9050db... (http://data.europa.eu/esco/skill/db9050db-ae5d-4be8-8114-c26f272c3bda): 21 αναφορές
  ► [LIGNITE JOBS] (Σύνολο Αναφορών: 488)
     • c4fe78ae... (http://data.europa.eu/esco/skill/c4fe78ae-8fef-4aa6-b767-146ed2b40198): 82 αναφορές
     • 35f1dcdc... (http://data.europa.eu/esco/skill/35f1dcdc-577f-46c6-96d9-6c7a64501de9): 20 αναφορές
     • 199f7919... (http://data.europa.eu/esco/skill/199f7919-5114-41b6-b6a5-41e0e4896ec1): 19 αναφορές
     • c5bc42be... (http://data.europa.eu/esco/skill/c5bc42be-4970-4dce-80e2-af78bae42e84): 15 αναφορές
     • 8d1dc94c... (http://data.europa.eu/esco/skill/8d1dc94c-d8e1-4ce6-92d5-a17ec0543dc9): 13 αναφορές

📍 ΧΩΡΑ: FRANCE
  ► [GREEN JOBS] (Σύνολο Αναφορών: 221742)
     • a06a0d41... (http://data.europa.eu/esco/skill/a06a0d41-10fa-4ba7-a988-e8b5eba966fb): 4953 αναφορές
     • c5bc42be... (http://data.europa.eu/esco/skill/c5bc42be-4970-4dce-80e2-af78bae42e84): 3139 αναφορές
     • 2b1ce548... (http://data.europa.eu/esco/skill/2b1ce548-4e16-45fb-bfb2-f3141c8efe8d): 2876 αναφορές
     • f3c5fae0... (http://data.europa.eu/esco/skill/f3c5fae0-c0e3-4410-bc09-62bd82d4cecc): 2786 αναφορές
     • 91abe492... (http://data.europa.eu/esco/skill/91abe492-18be-4cce-93c7-0dca07072363): 2471 αναφορές
  ► [LIGNITE JOBS] (Σύνολο Αναφορών: 165605)
     • c5bc42be... (http://data.europa.eu/esco/skill/c5bc42be-4970-4dce-80e2-af78bae42e84): 4995 αναφορές
     • a6354281... (http://data.europa.eu/esco/skill/a6354281-5578-46ac-a9db-d179d9962b98): 3462 αναφορές
     • 2b1ce548... (http://data.europa.eu/esco/skill/2b1ce548-4e16-45fb-bfb2-f3141c8efe8d): 2740 αναφορές
     • bf419e00... (http://data.europa.eu/esco/skill/bf419e00-8548-491a-a06f-d72ab439df2f): 2453 αναφορές
     • f3c5fae0... (http://data.europa.eu/esco/skill/f3c5fae0-c0e3-4410-bc09-62bd82d4cecc): 1883 αναφορές

📍 ΧΩΡΑ: GERMANY
  ► [GREEN JOBS] (Σύνολο Αναφορών: 157024)
     • 82887396... (http://data.europa.eu/esco/skill/82887396-e5bf-4306-af51-3fe8d82790b2): 2597 αναφορές
     • 8a1942a8... (http://data.europa.eu/esco/skill/8a1942a8-bebd-4cc5-bdff-fe215aaa3de5): 2404 αναφορές
     • b7cf2d84... (http://data.europa.eu/esco/skill/b7cf2d84-6c43-4baa-98cf-816a27336701): 2365 αναφορές
     • 5368a46a... (http://data.europa.eu/esco/skill/5368a46a-54b5-4874-a06f-964d557c1cfb): 2166 αναφορές
     • 351122a2... (http://data.europa.eu/esco/skill/351122a2-44f7-41db-ba8b-425136d5fb87): 2121 αναφορές
  ► [LIGNITE JOBS] (Σύνολο Αναφορών: 243280)
     • 6cb9c23b... (http://data.europa.eu/esco/skill/6cb9c23b-e3bc-4917-b588-26c4cef9d920): 8371 αναφορές
     • d88cb3f1... (http://data.europa.eu/esco/skill/d88cb3f1-8e02-4618-bf32-4b0488066934): 6741 αναφορές
     • c5bc42be... (http://data.europa.eu/esco/skill/c5bc42be-4970-4dce-80e2-af78bae42e84): 5010 αναφορές
     • 3e40c7d0... (http://data.europa.eu/esco/skill/3e40c7d0-0e36-4b33-bc33-0aa87eda0561): 4681 αναφορές
     • f4a6e9f7... (http://data.europa.eu/esco/skill/f4a6e9f7-5cff-46c0-894c-59c20bb78694): 3144 αναφορές

📍 ΧΩΡΑ: GREECE
  ► [GREEN JOBS] (Σύνολο Αναφορών: 26383)
     • cfccea88... (http://data.europa.eu/esco/skill/cfccea88-0558-40d4-b896-56a1e7993e24): 476 αναφορές
     • 4b406514... (http://data.europa.eu/esco/skill/4b406514-b3ed-4906-a347-7ebe6be52450): 475 αναφορές
     • f683ae1d... (http://data.europa.eu/esco/skill/f683ae1d-cb7c-4aa1-b9fe-205e1bd23535): 474 αναφορές
     • 15d76317... (http://data.europa.eu/esco/skill/15d76317-c71a-4fa2-aadc-2ecc34e627b7): 387 αναφορές
     • 199f7919... (http://data.europa.eu/esco/skill/199f7919-5114-41b6-b6a5-41e0e4896ec1): 324 αναφορές
  ► [LIGNITE JOBS] (Σύνολο Αναφορών: 18168)
     • c5bc42be... (http://data.europa.eu/esco/skill/c5bc42be-4970-4dce-80e2-af78bae42e84): 405 αναφορές
     • 6d3edede... (http://data.europa.eu/esco/skill/6d3edede-8951-4621-a835-e04323300fa0): 362 αναφορές
     • 199f7919... (http://data.europa.eu/esco/skill/199f7919-5114-41b6-b6a5-41e0e4896ec1): 309 αναφορές
     • f4a6e9f7... (http://data.europa.eu/esco/skill/f4a6e9f7-5cff-46c0-894c-59c20bb78694): 306 αναφορές
     • f683ae1d... (http://data.europa.eu/esco/skill/f683ae1d-cb7c-4aa1-b9fe-205e1bd23535): 296 αναφορές

📍 ΧΩΡΑ: ITALY
  ► [GREEN JOBS] (Σύνολο Αναφορών: 1381)
     • efb523d0... (http://data.europa.eu/esco/skill/efb523d0-c998-440d-8639-cd14ba841c4c): 143 αναφορές
     • 199f7919... (http://data.europa.eu/esco/skill/199f7919-5114-41b6-b6a5-41e0e4896ec1): 56 αναφορές
     • 2fb8480e... (http://data.europa.eu/esco/skill/2fb8480e-de3c-462b-b169-e8bbb344da68): 54 αναφορές
     • 538f8bc6... (http://data.europa.eu/esco/skill/538f8bc6-a5bf-422b-8112-5ad3fe9de9a0): 54 αναφορές
     • 6f8baa62... (http://data.europa.eu/esco/skill/6f8baa62-bc2b-4cc1-942b-f540c837cfa2): 54 αναφορές
  ► [LIGNITE JOBS] (Σύνολο Αναφορών: 4240)
     • efb523d0... (http://data.europa.eu/esco/skill/efb523d0-c998-440d-8639-cd14ba841c4c): 414 αναφορές
     • 6f8baa62... (http://data.europa.eu/esco/skill/6f8baa62-bc2b-4cc1-942b-f540c837cfa2): 306 αναφορές
     • 199f7919... (http://data.europa.eu/esco/skill/199f7919-5114-41b6-b6a5-41e0e4896ec1): 304 αναφορές
     • 2fb8480e... (http://data.europa.eu/esco/skill/2fb8480e-de3c-462b-b169-e8bbb344da68): 304 αναφορές
     • 538f8bc6... (http://data.europa.eu/esco/skill/538f8bc6-a5bf-422b-8112-5ad3fe9de9a0): 303 αναφορές

📍 ΧΩΡΑ: POLAND
  ► [GREEN JOBS] (Σύνολο Αναφορών: 1323)
     • 113b4428... (http://data.europa.eu/esco/skill/113b4428-0a31-4199-8496-070af7854b91): 33 αναφορές
     • f6d7ba88... (http://data.europa.eu/esco/skill/f6d7ba88-5234-4994-944d-843ca453c923): 27 αναφορές
     • f683ae1d... (http://data.europa.eu/esco/skill/f683ae1d-cb7c-4aa1-b9fe-205e1bd23535): 22 αναφορές
     • e36c1f47... (http://data.europa.eu/esco/skill/e36c1f47-3913-4d35-a6ae-fd9a7243483f): 21 αναφορές
     • 199f7919... (http://data.europa.eu/esco/skill/199f7919-5114-41b6-b6a5-41e0e4896ec1): 21 αναφορές
  ► [LIGNITE JOBS] (Σύνολο Αναφορών: 815)
     • 113b4428... (http://data.europa.eu/esco/skill/113b4428-0a31-4199-8496-070af7854b91): 24 αναφορές
     • ef6cb992... (http://data.europa.eu/esco/skill/ef6cb992-07d1-435b-a150-45d92228db1e): 23 αναφορές
     • d5e39a53... (http://data.europa.eu/esco/skill/d5e39a53-4f54-4d5f-9df3-b49664c9559d): 22 αναφορές
     • 978a76ca... (http://data.europa.eu/esco/skill/978a76ca-0d14-43b5-a69d-1996dfeb22de): 19 αναφορές
     • 59ea80e1... (http://data.europa.eu/esco/skill/59ea80e1-463a-4dba-82c6-d0b6d577d532): 18 αναφορές

📍 ΧΩΡΑ: ROMANIA
  ► [GREEN JOBS] (Σύνολο Αναφορών: 122)
     • fd082998... (http://data.europa.eu/esco/skill/fd082998-8cea-4abc-8504-03f7e4b7088e): 41 αναφορές
     • 2f4cdc7e... (http://data.europa.eu/esco/skill/2f4cdc7e-d98d-4e6c-9811-3dc28255c7ff): 18 αναφορές
     • 145fb42f... (http://data.europa.eu/esco/skill/145fb42f-ebee-48e2-bdf8-2e935edc7158): 3 αναφορές
     • e36c1f47... (http://data.europa.eu/esco/skill/e36c1f47-3913-4d35-a6ae-fd9a7243483f): 2 αναφορές
     • c662be22... (http://data.europa.eu/esco/skill/c662be22-f17a-4ba0-894f-d720b20c44cf): 2 αναφορές
  ► [LIGNITE JOBS] (Σύνολο Αναφορών: 0)
     Δεν βρέθηκαν skills.

📍 ΧΩΡΑ: SPAIN
  ► [GREEN JOBS] (Σύνολο Αναφορών: 1323)
     • c76ea1b8... (http://data.europa.eu/esco/skill/c76ea1b8-25a3-4084-a684-dcf10b7c880c): 24 αναφορές
     • 538f8bc6... (http://data.europa.eu/esco/skill/538f8bc6-a5bf-422b-8112-5ad3fe9de9a0): 23 αναφορές
     • 114a79ef... (http://data.europa.eu/esco/skill/114a79ef-1e62-475b-a862-954f5b4cca20): 22 αναφορές
     • 145fb42f... (http://data.europa.eu/esco/skill/145fb42f-ebee-48e2-bdf8-2e935edc7158): 19 αναφορές
     • c5bc42be... (http://data.europa.eu/esco/skill/c5bc42be-4970-4dce-80e2-af78bae42e84): 19 αναφορές
  ► [LIGNITE JOBS] (Σύνολο Αναφορών: 1057)
     • c5bc42be... (http://data.europa.eu/esco/skill/c5bc42be-4970-4dce-80e2-af78bae42e84): 50 αναφορές
     • e0ded9a1... (http://data.europa.eu/esco/skill/e0ded9a1-372d-46c8-80b5-ad994d606ef2): 35 αναφορές
     • c4fe78ae... (http://data.europa.eu/esco/skill/c4fe78ae-8fef-4aa6-b767-146ed2b40198): 29 αναφορές
     • bf419e00... (http://data.europa.eu/esco/skill/bf419e00-8548-491a-a06f-d72ab439df2f): 26 αναφορές
     • 2bbdea06... (http://data.europa.eu/esco/skill/2bbdea06-a265-42b5-bb4f-7241b661f069): 26 αναφορές

📍 ΧΩΡΑ: SWEDEN
  ► [GREEN JOBS] (Σύνολο Αναφορών: 293180)
     • 65715f7a... (http://data.europa.eu/esco/skill/65715f7a-c791-416b-b88a-2933a1c81647): 8377 αναφορές
     • 7ee51257... (http://data.europa.eu/esco/skill/7ee51257-8947-4b69-9bdf-322baf0a6398): 8095 αναφορές
     • 538f8bc6... (http://data.europa.eu/esco/skill/538f8bc6-a5bf-422b-8112-5ad3fe9de9a0): 7031 αναφορές
     • 082967d4... (http://data.europa.eu/esco/skill/082967d4-b94c-4305-aa13-35a6aa8c5c7c): 4846 αναφορές
     • 0da516ee... (http://data.europa.eu/esco/skill/0da516ee-e70e-4384-be13-f5ff80be8127): 3422 αναφορές
  ► [LIGNITE JOBS] (Σύνολο Αναφορών: 190611)
     • 7ee51257... (http://data.europa.eu/esco/skill/7ee51257-8947-4b69-9bdf-322baf0a6398): 5344 αναφορές
     • 65715f7a... (http://data.europa.eu/esco/skill/65715f7a-c791-416b-b88a-2933a1c81647): 4793 αναφορές
     • 0da516ee... (http://data.europa.eu/esco/skill/0da516ee-e70e-4384-be13-f5ff80be8127): 2762 αναφορές
     • 082967d4... (http://data.europa.eu/esco/skill/082967d4-b94c-4305-aa13-35a6aa8c5c7c): 2536 αναφορές
     • f4a6e9f7... (http://data.europa.eu/esco/skill/f4a6e9f7-5cff-46c0-894c-59c20bb78694): 2533 αναφορές

================================================================================
 2. TOP-5 ΔΕΞΙΟΤΗΤΕΣ ΕΡΓΑΖΟΜΕΝΩΝ ΑΝΑ ΧΩΡΑ (PROFILES)
================================================================================

📍 ΧΩΡΑ: CZECHIA
  ► [GREEN PROFILES] (Σύνολο Αναφορών: 1007)
     • cd5efa8c... (http://data.europa.eu/esco/skill/cd5efa8c-e44d-4cbc-91c6-796018dbed68): 21 αναφορές
     • 15d76317... (http://data.europa.eu/esco/skill/15d76317-c71a-4fa2-aadc-2ecc34e627b7): 13 αναφορές
     • bda0d115... (http://data.europa.eu/esco/skill/bda0d115-f315-453e-99dc-f8b0e5862db3): 12 αναφορές
     • 538f8bc6... (http://data.europa.eu/esco/skill/538f8bc6-a5bf-422b-8112-5ad3fe9de9a0): 11 αναφορές
     • 9531fe02... (http://data.europa.eu/esco/skill/9531fe02-1e1f-4a36-95f7-a76a77cd4b8d): 10 αναφορές
  ► [LIGNITE PROFILES] (Σύνολο Αναφορών: 999)
     • cd5efa8c... (http://data.europa.eu/esco/skill/cd5efa8c-e44d-4cbc-91c6-796018dbed68): 18 αναφορές
     • ccd0a1d9... (http://data.europa.eu/esco/skill/ccd0a1d9-afda-43d9-b901-96344886e14d): 14 αναφορές
     • f4a6e9f7... (http://data.europa.eu/esco/skill/f4a6e9f7-5cff-46c0-894c-59c20bb78694): 12 αναφορές
     • f0de4973... (http://data.europa.eu/esco/skill/f0de4973-0a70-4644-8fd4-3a97080476f4): 11 αναφορές
     • 75b30aeb... (http://data.europa.eu/esco/skill/75b30aeb-34c0-40f4-b77d-271d75a98b14): 10 αναφορές

📍 ΧΩΡΑ: FRANCE
  ► [GREEN PROFILES] (Σύνολο Αναφορών: 8108)
     • cd5efa8c... (http://data.europa.eu/esco/skill/cd5efa8c-e44d-4cbc-91c6-796018dbed68): 170 αναφορές
     • 15d76317... (http://data.europa.eu/esco/skill/15d76317-c71a-4fa2-aadc-2ecc34e627b7): 101 αναφορές
     • 2fb8480e... (http://data.europa.eu/esco/skill/2fb8480e-de3c-462b-b169-e8bbb344da68): 97 αναφορές
     • 19a8293b... (http://data.europa.eu/esco/skill/19a8293b-8e95-4de3-983f-77484079c389): 81 αναφορές
     • ccd0a1d9... (http://data.europa.eu/esco/skill/ccd0a1d9-afda-43d9-b901-96344886e14d): 76 αναφορές
  ► [LIGNITE PROFILES] (Σύνολο Αναφορών: 6106)
     • cd5efa8c... (http://data.europa.eu/esco/skill/cd5efa8c-e44d-4cbc-91c6-796018dbed68): 108 αναφορές
     • 2fb8480e... (http://data.europa.eu/esco/skill/2fb8480e-de3c-462b-b169-e8bbb344da68): 93 αναφορές
     • ccd0a1d9... (http://data.europa.eu/esco/skill/ccd0a1d9-afda-43d9-b901-96344886e14d): 81 αναφορές
     • 15d76317... (http://data.europa.eu/esco/skill/15d76317-c71a-4fa2-aadc-2ecc34e627b7): 69 αναφορές
     • c5bc42be... (http://data.europa.eu/esco/skill/c5bc42be-4970-4dce-80e2-af78bae42e84): 59 αναφορές

📍 ΧΩΡΑ: GERMANY
  ► [GREEN PROFILES] (Σύνολο Αναφορών: 9257)
     • cd5efa8c... (http://data.europa.eu/esco/skill/cd5efa8c-e44d-4cbc-91c6-796018dbed68): 212 αναφορές
     • 538f8bc6... (http://data.europa.eu/esco/skill/538f8bc6-a5bf-422b-8112-5ad3fe9de9a0): 135 αναφορές
     • 2fb8480e... (http://data.europa.eu/esco/skill/2fb8480e-de3c-462b-b169-e8bbb344da68): 118 αναφορές
     • ccd0a1d9... (http://data.europa.eu/esco/skill/ccd0a1d9-afda-43d9-b901-96344886e14d): 79 αναφορές
     • 9531fe02... (http://data.europa.eu/esco/skill/9531fe02-1e1f-4a36-95f7-a76a77cd4b8d): 78 αναφορές
  ► [LIGNITE PROFILES] (Σύνολο Αναφορών: 7237)
     • cd5efa8c... (http://data.europa.eu/esco/skill/cd5efa8c-e44d-4cbc-91c6-796018dbed68): 121 αναφορές
     • ccd0a1d9... (http://data.europa.eu/esco/skill/ccd0a1d9-afda-43d9-b901-96344886e14d): 93 αναφορές
     • 2fb8480e... (http://data.europa.eu/esco/skill/2fb8480e-de3c-462b-b169-e8bbb344da68): 80 αναφορές
     • f4a6e9f7... (http://data.europa.eu/esco/skill/f4a6e9f7-5cff-46c0-894c-59c20bb78694): 58 αναφορές
     • c3a03c5a... (http://data.europa.eu/esco/skill/c3a03c5a-c260-4c26-9b9a-873abb396f4d): 57 αναφορές

📍 ΧΩΡΑ: GREECE
  ► [GREEN PROFILES] (Σύνολο Αναφορών: 3157)
     • cd5efa8c... (http://data.europa.eu/esco/skill/cd5efa8c-e44d-4cbc-91c6-796018dbed68): 60 αναφορές
     • 538f8bc6... (http://data.europa.eu/esco/skill/538f8bc6-a5bf-422b-8112-5ad3fe9de9a0): 48 αναφορές
     • a2b5dcf3... (http://data.europa.eu/esco/skill/a2b5dcf3-5b6a-453d-876c-cff540c0faf1): 39 αναφορές
     • 7f18039d... (http://data.europa.eu/esco/skill/7f18039d-dfae-471b-9daa-507f6b2d2842): 33 αναφορές
     • fc4fcb4b... (http://data.europa.eu/esco/skill/fc4fcb4b-993f-4f2c-b158-c2171ec18ed8): 33 αναφορές
  ► [LIGNITE PROFILES] (Σύνολο Αναφορών: 1973)
     • cd5efa8c... (http://data.europa.eu/esco/skill/cd5efa8c-e44d-4cbc-91c6-796018dbed68): 23 αναφορές
     • f4a6e9f7... (http://data.europa.eu/esco/skill/f4a6e9f7-5cff-46c0-894c-59c20bb78694): 23 αναφορές
     • 15d76317... (http://data.europa.eu/esco/skill/15d76317-c71a-4fa2-aadc-2ecc34e627b7): 23 αναφορές
     • 538f8bc6... (http://data.europa.eu/esco/skill/538f8bc6-a5bf-422b-8112-5ad3fe9de9a0): 17 αναφορές
     • ccd0a1d9... (http://data.europa.eu/esco/skill/ccd0a1d9-afda-43d9-b901-96344886e14d): 16 αναφορές

📍 ΧΩΡΑ: ITALY
  ► [GREEN PROFILES] (Σύνολο Αναφορών: 9453)
     • cd5efa8c... (http://data.europa.eu/esco/skill/cd5efa8c-e44d-4cbc-91c6-796018dbed68): 205 αναφορές
     • 538f8bc6... (http://data.europa.eu/esco/skill/538f8bc6-a5bf-422b-8112-5ad3fe9de9a0): 117 αναφορές
     • 14ced458... (http://data.europa.eu/esco/skill/14ced458-5f4b-495f-bd3d-9c240614bda0): 117 αναφορές
     • 2fb8480e... (http://data.europa.eu/esco/skill/2fb8480e-de3c-462b-b169-e8bbb344da68): 106 αναφορές
     • 97965983... (http://data.europa.eu/esco/skill/97965983-0da4-4902-9daf-d5cd2693ef73): 106 αναφορές
  ► [LIGNITE PROFILES] (Σύνολο Αναφορών: 5985)
     • cd5efa8c... (http://data.europa.eu/esco/skill/cd5efa8c-e44d-4cbc-91c6-796018dbed68): 121 αναφορές
     • 2fb8480e... (http://data.europa.eu/esco/skill/2fb8480e-de3c-462b-b169-e8bbb344da68): 74 αναφορές
     • b633eb55... (http://data.europa.eu/esco/skill/b633eb55-8f1f-4ae6-ab4c-2022ffe2cb7f): 51 αναφορές
     • ccd0a1d9... (http://data.europa.eu/esco/skill/ccd0a1d9-afda-43d9-b901-96344886e14d): 40 αναφορές
     • f4a6e9f7... (http://data.europa.eu/esco/skill/f4a6e9f7-5cff-46c0-894c-59c20bb78694): 40 αναφορές

📍 ΧΩΡΑ: POLAND
  ► [GREEN PROFILES] (Σύνολο Αναφορών: 3262)
     • cd5efa8c... (http://data.europa.eu/esco/skill/cd5efa8c-e44d-4cbc-91c6-796018dbed68): 60 αναφορές
     • 19a8293b... (http://data.europa.eu/esco/skill/19a8293b-8e95-4de3-983f-77484079c389): 40 αναφορές
     • ccd0a1d9... (http://data.europa.eu/esco/skill/ccd0a1d9-afda-43d9-b901-96344886e14d): 32 αναφορές
     • f0de4973... (http://data.europa.eu/esco/skill/f0de4973-0a70-4644-8fd4-3a97080476f4): 29 αναφορές
     • 598de5b0... (http://data.europa.eu/esco/skill/598de5b0-5b58-4ea7-8058-a4bc4d18c742): 29 αναφορές
  ► [LIGNITE PROFILES] (Σύνολο Αναφορών: 3080)
     • cd5efa8c... (http://data.europa.eu/esco/skill/cd5efa8c-e44d-4cbc-91c6-796018dbed68): 45 αναφορές
     • ccd0a1d9... (http://data.europa.eu/esco/skill/ccd0a1d9-afda-43d9-b901-96344886e14d): 42 αναφορές
     • 75b30aeb... (http://data.europa.eu/esco/skill/75b30aeb-34c0-40f4-b77d-271d75a98b14): 40 αναφορές
     • 2fb8480e... (http://data.europa.eu/esco/skill/2fb8480e-de3c-462b-b169-e8bbb344da68): 31 αναφορές
     • 15d76317... (http://data.europa.eu/esco/skill/15d76317-c71a-4fa2-aadc-2ecc34e627b7): 29 αναφορές

📍 ΧΩΡΑ: ROMANIA
  ► [GREEN PROFILES] (Σύνολο Αναφορών: 2578)
     • cd5efa8c... (http://data.europa.eu/esco/skill/cd5efa8c-e44d-4cbc-91c6-796018dbed68): 59 αναφορές
     • 15d76317... (http://data.europa.eu/esco/skill/15d76317-c71a-4fa2-aadc-2ecc34e627b7): 30 αναφορές
     • fc4fcb4b... (http://data.europa.eu/esco/skill/fc4fcb4b-993f-4f2c-b158-c2171ec18ed8): 29 αναφορές
     • 14ced458... (http://data.europa.eu/esco/skill/14ced458-5f4b-495f-bd3d-9c240614bda0): 29 αναφορές
     • 450de541... (http://data.europa.eu/esco/skill/450de541-797a-4da0-9fe4-a81471c8047d): 27 αναφορές
  ► [LIGNITE PROFILES] (Σύνολο Αναφορών: 1928)
     • cd5efa8c... (http://data.europa.eu/esco/skill/cd5efa8c-e44d-4cbc-91c6-796018dbed68): 33 αναφορές
     • 15d76317... (http://data.europa.eu/esco/skill/15d76317-c71a-4fa2-aadc-2ecc34e627b7): 30 αναφορές
     • cf310cff... (http://data.europa.eu/esco/skill/cf310cff-0d28-4dbc-9dbb-cc500a3196c2): 25 αναφορές
     • c5bc42be... (http://data.europa.eu/esco/skill/c5bc42be-4970-4dce-80e2-af78bae42e84): 22 αναφορές
     • ccd0a1d9... (http://data.europa.eu/esco/skill/ccd0a1d9-afda-43d9-b901-96344886e14d): 21 αναφορές

📍 ΧΩΡΑ: SPAIN
  ► [GREEN PROFILES] (Σύνολο Αναφορών: 8429)
     • cd5efa8c... (http://data.europa.eu/esco/skill/cd5efa8c-e44d-4cbc-91c6-796018dbed68): 176 αναφορές
     • 9fc400ac... (http://data.europa.eu/esco/skill/9fc400ac-8ed2-4aff-915f-aa4f2609ec7b): 170 αναφορές
     • 89ff28d6... (http://data.europa.eu/esco/skill/89ff28d6-342c-435d-83aa-83e71dbbbc96): 104 αναφορές
     • 538f8bc6... (http://data.europa.eu/esco/skill/538f8bc6-a5bf-422b-8112-5ad3fe9de9a0): 98 αναφορές
     • 2fb8480e... (http://data.europa.eu/esco/skill/2fb8480e-de3c-462b-b169-e8bbb344da68): 96 αναφορές
  ► [LIGNITE PROFILES] (Σύνολο Αναφορών: 5867)
     • cd5efa8c... (http://data.europa.eu/esco/skill/cd5efa8c-e44d-4cbc-91c6-796018dbed68): 79 αναφορές
     • 2fb8480e... (http://data.europa.eu/esco/skill/2fb8480e-de3c-462b-b169-e8bbb344da68): 74 αναφορές
     • 9fc400ac... (http://data.europa.eu/esco/skill/9fc400ac-8ed2-4aff-915f-aa4f2609ec7b): 71 αναφορές
     • ccd0a1d9... (http://data.europa.eu/esco/skill/ccd0a1d9-afda-43d9-b901-96344886e14d): 67 αναφορές
     • c3a03c5a... (http://data.europa.eu/esco/skill/c3a03c5a-c260-4c26-9b9a-873abb396f4d): 51 αναφορές

📍 ΧΩΡΑ: SWEDEN
  ► [GREEN PROFILES] (Σύνολο Αναφορών: 3599)
     • cd5efa8c... (http://data.europa.eu/esco/skill/cd5efa8c-e44d-4cbc-91c6-796018dbed68): 97 αναφορές
     • 538f8bc6... (http://data.europa.eu/esco/skill/538f8bc6-a5bf-422b-8112-5ad3fe9de9a0): 63 αναφορές
     • dba46f87... (http://data.europa.eu/esco/skill/dba46f87-0831-49cd-a1c7-340a653c0221): 39 αναφορές

   Country  Green Jobs  Lignite Jobs  Green/Lignite Ratio  Common Skills
0  Czechia         371           237                 1.57             80
1   France       40702         38154                 1.07           3572
2  Germany       23789         48009                 0.50           3469
3   Greece        3624          2887                 1.26           1260
4    Italy         246           514                 0.48             85
5   Poland         545           391                 1.39            134
6  Romania          76             0                  NaN              0
7    Spain         898           965                 0.93            149
8   Sweden       34397         24004                 1.43           3702

================================================================================
 5. SKILL MATCHING SCORE & GAP ANALYSIS (LIGNITE PROFILES VS GREEN JOBS)
================================================================================

,Country,Lignite Profile Skills,Green Job Skills Needed,Skill Matching Score (%)
0,Czechia,531,569,23.16
1,France,1567,5175,88.39
2,Germany,1767,4782,72.95
3,Greece,894,2320,68.90
4,Italy,1669,309,11.20
5,Poland,1072,517,18.10
6,Romania,837,61,2.99
7,Spain,1583,586,16.93
8,Sweden,1050,5402,94.29

#claude

In [4]:
from collections import Counter
import json
import os
import numpy as np
import pandas as pd

# ==============================================================================
# 0. ΡΥΘΜΙΣΕΙΣ
# ==============================================================================
# Colab: τα αρχεία που ανεβάζεις εμφανίζονται συνήθως στο /content
BASE_DIR = "/content"

COUNTRIES = ["czechia", "france", "germany", "greece", "italy",
             "poland", "romania", "spain", "sweden"]
CATEGORIES = ["green", "lignite"]
KINDS = ["jobs", "profiles"]

# ==============================================================================
# 1. MAPPERS: ΦΟΡΤΩΣΗ CSV ΓΙΑ ΜΕΤΑΤΡΟΠΗ URIs ΣΕ ΑΝΑΓΝΩΣΙΜΑ ΟΝΟΜΑΤΑ
# ==============================================================================
def build_label_map(path):
    """Διαβάζει ένα ESCO-style CSV και φτιάχνει dict URI -> preferredLabel.
    Εντοπίζει αυτόματα τις σωστές στήλες ακόμη κι αν δεν λέγονται ακριβώς
    'conceptUri' / 'preferredLabel'."""
    if not os.path.exists(path):
        print(f"⚠️ Δεν βρέθηκε: {path} — τα URIs αυτής της κατηγορίας θα εμφανίζονται ως έχουν.")
        return {}
    df_ref = pd.read_csv(path)

    uri_col = None
    for col in df_ref.columns:
        sample = df_ref[col].dropna().astype(str).head(20)
        if sample.str.startswith("http://data.europa.eu/esco/").any():
            uri_col = col
            break

    label_col = None
    for col in df_ref.columns:
        if "preferredlabel" in col.lower().replace("_", ""):
            label_col = col
            break
    if label_col is None:
        # fallback: πρώτη στήλη τύπου string που δεν είναι η uri_col
        for col in df_ref.columns:
            if col != uri_col and df_ref[col].dtype == object:
                label_col = col
                break

    if uri_col is None or label_col is None:
        print(f"⚠️ Δεν εντοπίστηκαν στήλες URI/label στο {path}. Στήλες: {list(df_ref.columns)}")
        return {}

    mapping = dict(zip(df_ref[uri_col].astype(str).str.strip(), df_ref[label_col]))
    print(f"✅ {path}: φορτώθηκαν {len(mapping)} αντιστοιχίσεις (στήλες: '{uri_col}' -> '{label_col}').")
    return mapping

# --- Occupations: συνδυάζουμε τα δύο δικά σου curated αρχεία ---
green_occ_map = build_label_map(f"{BASE_DIR}/highly_green_occupations.csv")
lignite_occ_map = build_label_map(f"{BASE_DIR}/lignite_occupations.csv")
esco_occ_map = {**green_occ_map, **lignite_occ_map}
print(f"➡️ Σύνολο μοναδικών occupation labels διαθέσιμων: {len(esco_occ_map)}\n")

# --- Skills: προαιρετικό, αν έχεις κάποιο σχετικό αρχείο τοπικά θα αντιστοιχιστεί,
#     αλλιώς θα εμφανίζεται το κομμένο URI (όπως έκανε και ο αρχικός κώδικας) ---
esco_skill_map = {}
for candidate in ["skills_en.csv", "greenSkillsCollection_en.csv"]:
    m = build_label_map(f"{BASE_DIR}/{candidate}")
    esco_skill_map.update(m)
print(f"➡️ Σύνολο μοναδικών skill labels διαθέσιμων: {len(esco_skill_map)}\n")

def is_isco_uri(uri):
    return "/esco/isco/" in uri

def get_occ_name(uri):
    if uri in esco_occ_map:
        return esco_occ_map[uri]
    if is_isco_uri(uri):
        return f"ISCO Code: {uri.split('/')[-1]}"
    return uri.split("/")[-1]

def get_skill_name(uri):
    if uri in esco_skill_map:
        return esco_skill_map[uri]
    return uri.split("/")[-1][:8] + "..." if "/" in uri else uri

# ==============================================================================
# 2. ΦΟΡΤΩΣΗ ΚΑΙ ΤΩΝ 36 DATASETS (ΜΕ SAFETY CHECKS)
# ==============================================================================
def load_records_safe(path):
    if not os.path.exists(path):
        if os.path.exists(f"{path}.json"):
            path = f"{path}.json"
        else:
            return []
    with open(path, "r", encoding="utf-8") as f:
        content = f.read()
    try:
        data_ = json.loads(content)
        if isinstance(data_, list):
            return [x for x in data_ if isinstance(x, dict)]
        elif isinstance(data_, dict):
            for v in data_.values():
                if isinstance(v, list):
                    return [x for x in v if isinstance(x, dict)]
            return [data_]
    except json.JSONDecodeError:
        pass
    records = []
    for line in content.splitlines():
        line = line.strip().rstrip(",")
        if not line or line in ("[", "]", "{", "}"):
            continue
        try:
            item = json.loads(line)
            if isinstance(item, dict):
                records.append(item)
        except json.JSONDecodeError:
            continue
    return records

data = {"jobs": {"green": {}, "lignite": {}}, "profiles": {"green": {}, "lignite": {}}}
for kind in KINDS:
    for category in CATEGORIES:
        for country in COUNTRIES:
            p = f"{BASE_DIR}/{kind}_{country}_{category}_clean.json"
            data[kind][category][country] = load_records_safe(p)

print("✅ Η φόρτωση των 36 datasets ολοκληρώθηκε!\n")

# Γρήγορο overview μεγεθών datasets
summary_rows = [
    {"kind": kind, "category": category, "country": country, "n_records": len(recs)}
    for kind in data for category in data[kind] for country, recs in data[kind][category].items()
]
df_summary = pd.DataFrame(summary_rows)
display(df_summary.pivot_table(index=["kind", "category"], columns="country", values="n_records"))

✅ /content/highly_green_occupations.csv: φορτώθηκαν 152 αντιστοιχίσεις (στήλες: 'conceptUri' -> 'preferredLabel').
✅ /content/lignite_occupations.csv: φορτώθηκαν 122 αντιστοιχίσεις (στήλες: 'conceptUri' -> 'preferredLabel').
➡️ Σύνολο μοναδικών occupation labels διαθέσιμων: 263

⚠️ Δεν βρέθηκε: /content/skills_en.csv — τα URIs αυτής της κατηγορίας θα εμφανίζονται ως έχουν.
✅ /content/greenSkillsCollection_en.csv: φορτώθηκαν 629 αντιστοιχίσεις (στήλες: 'conceptUri' -> 'preferredLabel').
➡️ Σύνολο μοναδικών skill labels διαθέσιμων: 629

✅ Η φόρτωση των 36 datasets ολοκληρώθηκε!

country            czechia   france  germany  greece    italy  poland  \
kind     category
jobs     green       371.0  40702.0  23789.0  3624.0    246.0   545.0
         lignite     237.0  38154.0  48009.0  2887.0    514.0   391.0
profiles green      3064.0  54369.0  34557.0  4913.0  37320.0  8744.0
         lignite    3036.0  45233.0  25707.0  3247.0  23290.0  8731.0

country            romania    spain   sweden
kind     category
jobs     green        76.0    898.0      0.0
         lignite       0.0    965.0  24004.0
profiles green      7997.0  27707.0  10136.0
         lignite    5157.0  21843.0   9100.0

In [5]:
# ==============================================================================
# 1. TOP-5 ZΗΤΟΥΜΕΝΕΣ ΔΕΞΙΟΤΗΤΕΣ (JOBS) ΑΝΑ ΧΩΡΑ — green/lignite ξεχωριστά
# ==============================================================================
print("=" * 80)
print(" 1. TOP-5 ΖΗΤΟΥΜΕΝΕΣ ΔΕΞΙΟΤΗΤΕΣ (SKILLS) ΑΝΑ ΧΩΡΑ (JOBS) ")
print("=" * 80)

for country in COUNTRIES:
    print(f"\n📍 ΧΩΡΑ: {country.upper()}")
    for cat in CATEGORIES:
        jobs = data["jobs"][cat].get(country, [])
        skills_list = [s for j in jobs for s in j.get("skills", []) if s]
        top_skills = Counter(skills_list).most_common(5)
        print(f"  ► [{cat.upper()} JOBS] (Σύνολο αναφορών: {len(skills_list)})")
        if not top_skills:
            print("     Δεν βρέθηκαν skills.")
        for sk_uri, count in top_skills:
            print(f"     • {get_skill_name(sk_uri)}: {count} αναφορές")

# ==============================================================================
# 2. TOP-5 ΔΕΞΙΟΤΗΤΕΣ ΕΡΓΑΖΟΜΕΝΩΝ (PROFILES) ΑΝΑ ΧΩΡΑ + fill-rate έλεγχος
# ==============================================================================
print("\n" + "=" * 80)
print(" 2. TOP-5 ΔΕΞΙΟΤΗΤΕΣ ΕΡΓΑΖΟΜΕΝΩΝ ΑΝΑ ΧΩΡΑ (PROFILES) ")
print("=" * 80)

print("\n--- Fill-rate πεδίου 'skills' στα profiles (πόσο αξιόπιστο είναι το top-5) ---")
fill_rows = []
for cat in CATEGORIES:
    for country in COUNTRIES:
        profs = data["profiles"][cat].get(country, [])
        total = len(profs)
        with_skills = sum(1 for p in profs if p.get("skills"))
        pct = round(with_skills / total * 100, 1) if total else 0.0
        fill_rows.append({"category": cat, "country": country, "total": total,
                           "with_skills": with_skills, "fill_rate_%": pct})
df_fill = pd.DataFrame(fill_rows)
display(df_fill)

for country in COUNTRIES:
    print(f"\n📍 ΧΩΡΑ: {country.upper()}")
    for cat in CATEGORIES:
        profiles = data["profiles"][cat].get(country, [])
        skills_list = [s for prof in profiles for s in prof.get("skills", []) if s]
        top_skills = Counter(skills_list).most_common(5)
        print(f"  ► [{cat.upper()} PROFILES] (Σύνολο αναφορών: {len(skills_list)})")
        if not top_skills:
            print("     Δεν βρέθηκαν skills.")
        for sk_uri, count in top_skills:
            print(f"     • {get_skill_name(sk_uri)}: {count} αναφορές")

# ==============================================================================
# 3. TOP-5 ΣΥΓΚΕΚΡΙΜΕΝΑ OCCUPATIONS ΣΤΙΣ ΑΓΓΕΛΙΕΣ (εξαιρούνται τα ISCO group URIs)
# ==============================================================================
print("\n" + "=" * 80)
print(" 3. TOP-5 ΠΙΟ ΣΥΧΝΑ ΕΠΑΓΓΕΛΜΑΤΑ ΣΤΙΣ ΑΓΓΕΛΙΕΣ (JOBS) ")
print("=" * 80)

for country in COUNTRIES:
    print(f"\n📍 ΧΩΡΑ: {country.upper()}")
    for cat in CATEGORIES:
        jobs = data["jobs"][cat].get(country, [])
        occs_list = [o for j in jobs for o in j.get("occupations", [])
                     if o and not is_isco_uri(o)]
        top_occs = Counter(occs_list).most_common(5)
        print(f"  ► [{cat.upper()} JOBS]")
        if not top_occs:
            print("     Δεν βρέθηκαν occupations.")
        for occ_uri, count in top_occs:
            print(f"     • {get_occ_name(occ_uri)}: {count} αγγελίες")

# ==============================================================================
# 4. ΚΛΑΔΟΙ (SECTORS): ΠΟΙΟΙ ΚΥΡΙΑΡΧΟΥΝ ΣΤΟ GREEN vs LIGNITE ΑΝΑ ΧΩΡΑ
# ==============================================================================
print("\n" + "=" * 80)
print(" 4. ΣΥΓΚΡΙΣΗ ΚΛΑΔΩΝ (SECTORS): GREEN VS LIGNITE ")
print("=" * 80)

for country in COUNTRIES:
    green_sectors = Counter(s for j in data["jobs"]["green"].get(country, [])
                             for s in j.get("sectors", []) if s)
    lignite_sectors = Counter(s for j in data["jobs"]["lignite"].get(country, [])
                               for s in j.get("sectors", []) if s)
    all_sectors = set(green_sectors) | set(lignite_sectors)
    ranked = sorted(all_sectors,
                     key=lambda s: green_sectors.get(s, 0) - lignite_sectors.get(s, 0),
                     reverse=True)

    print(f"\n📍 {country.upper()}")
    print("  Κλάδοι που κυριαρχούν στο GREEN:")
    for s in ranked[:5]:
        print(f"     • {s}: green={green_sectors.get(s,0)} vs lignite={lignite_sectors.get(s,0)}")
    print("  Κλάδοι που κυριαρχούν στο LIGNITE:")
    for s in reversed(ranked[-5:]):
        print(f"     • {s}: lignite={lignite_sectors.get(s,0)} vs green={green_sectors.get(s,0)}")

# ==============================================================================
# 5. ΣΥΓΚΡΙΤΙΚΗ ΑΝΑΛΥΣΗ: GREEN VS LIGNITE JOBS (λόγος + κοινές δεξιότητες)
# ==============================================================================
print("\n" + "=" * 80)
print(" 5. GREEN VS LIGNITE JOBS — ΛΟΓΟΣ & ΚΟΙΝΕΣ ΔΕΞΙΟΤΗΤΕΣ (ΓΕΦΥΡΕΣ) ")
print("=" * 80)

transition_stats = []
for country in COUNTRIES:
    n_green = len(data["jobs"]["green"].get(country, []))
    n_lignite = len(data["jobs"]["lignite"].get(country, []))
    ratio = round(n_green / n_lignite, 2) if n_lignite > 0 else np.nan

    green_skills = set(s for j in data["jobs"]["green"].get(country, [])
                        for s in j.get("skills", []) if s)
    lignite_skills = set(s for j in data["jobs"]["lignite"].get(country, [])
                          for s in j.get("skills", []) if s)
    common_skills = green_skills & lignite_skills

    transition_stats.append({
        "Country": country.capitalize(),
        "Green Jobs": n_green,
        "Lignite Jobs": n_lignite,
        "Green/Lignite Ratio": ratio,
        "Common Skills (count)": len(common_skills),
    })

df_trans = pd.DataFrame(transition_stats)
display(df_trans)

print("\n--- Ονόματα δεξιοτήτων-γεφυρών (κοινές lignite ↔ green jobs) ---")
for country in COUNTRIES:
    green_skills = set(s for j in data["jobs"]["green"].get(country, [])
                        for s in j.get("skills", []) if s)
    lignite_skills = set(s for j in data["jobs"]["lignite"].get(country, [])
                          for s in j.get("skills", []) if s)
    common = green_skills & lignite_skills
    print(f"\n📍 {country.upper()} — {len(common)} κοινές δεξιότητες (top 10):")
    for uri in list(common)[:10]:
        print(f"   • {get_skill_name(uri)}")

# ==============================================================================
# 6. SKILL MATCHING SCORE & GAP ANALYSIS (LIGNITE PROFILES VS GREEN JOBS)
# ==============================================================================
print("\n" + "=" * 80)
print(" 6. SKILL MATCHING SCORE & GAP ANALYSIS (LIGNITE PROFILES VS GREEN JOBS) ")
print("=" * 80)

match_results = []
gap_rows = []

for country in COUNTRIES:
    lignite_prof_skills = set(s for p in data["profiles"]["lignite"].get(country, [])
                               for s in p.get("skills", []) if s)

    green_job_skills_counter = Counter(
        s for j in data["jobs"]["green"].get(country, [])
        for s in j.get("skills", []) if s
    )
    green_job_skills_set = set(green_job_skills_counter.keys())

    if len(lignite_prof_skills) > 0:
        matched = lignite_prof_skills & green_job_skills_set
        score = round((len(matched) / len(lignite_prof_skills)) * 100, 2)
    else:
        score = np.nan  # δεν υπάρχουν δεδομένα -> άγνωστο, όχι 0%

    match_results.append({
        "Country": country.capitalize(),
        "Lignite Profile Skills": len(lignite_prof_skills),
        "Green Job Skills Needed": len(green_job_skills_set),
        "Skill Matching Score (%)": score,
    })

    # Gap analysis: skills που ζητούνται πολύ σε green jobs αλλά λείπουν από lignite profiles
    gaps = [(uri, cnt) for uri, cnt in green_job_skills_counter.most_common()
            if uri not in lignite_prof_skills]
    for uri, cnt in gaps[:10]:
        gap_rows.append({
            "Country": country.capitalize(),
            "Missing Skill": get_skill_name(uri),
            "Demand in Green Jobs": cnt,
        })

df_match = pd.DataFrame(match_results)
print("\n--- Skill Matching Score (ετοιμότητα lignite → green) ---")
display(df_match.sort_values("Skill Matching Score (%)", ascending=False))

df_gap = pd.DataFrame(gap_rows)
print("\n--- Top Skill Gaps ανά χώρα (μεγάλη ζήτηση, απούσα από lignite profiles) ---")
for country in COUNTRIES:
    sub = df_gap[df_gap["Country"] == country.capitalize()]
    if sub.empty:
        continue
    print(f"\n📍 {country.upper()}")
    display(sub.reset_index(drop=True))

================================================================================
 1. TOP-5 ΖΗΤΟΥΜΕΝΕΣ ΔΕΞΙΟΤΗΤΕΣ (SKILLS) ΑΝΑ ΧΩΡΑ (JOBS)
================================================================================

📍 ΧΩΡΑ: CZECHIA
  ► [GREEN JOBS] (Σύνολο αναφορών: 1291)
     • 199f7919...: 47 αναφορές
     • operate water purifying equipment: 36 αναφορές
     • manage water distribution procedures: 28 αναφορές
     • promote animal welfare: 24 αναφορές
     • manage health and safety: 21 αναφορές
  ► [LIGNITE JOBS] (Σύνολο αναφορών: 488)
     • c4fe78ae...: 82 αναφορές
     • 35f1dcdc...: 20 αναφορές
     • 199f7919...: 19 αναφορές
     • c5bc42be...: 15 αναφορές
     • 8d1dc94c...: 13 αναφορές

📍 ΧΩΡΑ: FRANCE
  ► [GREEN JOBS] (Σύνολο αναφορών: 221742)
     • a06a0d41...: 4953 αναφορές
     • c5bc42be...: 3139 αναφορές
     • 2b1ce548...: 2876 αναφορές
     • f3c5fae0...: 2786 αναφορές
     • 91abe492...: 2471 αναφορές
  ► [LIGNITE JOBS] (Σύνολο αναφορών: 165605)
     • c5bc42be...: 4995 αναφορές
     • a6354281...: 3462 αναφορές
     • 2b1ce548...: 2740 αναφορές
     • bf419e00...: 2453 αναφορές
     • f3c5fae0...: 1883 αναφορές

📍 ΧΩΡΑ: GERMANY
  ► [GREEN JOBS] (Σύνολο αναφορών: 157024)
     • 82887396...: 2597 αναφορές
     • 8a1942a8...: 2404 αναφορές
     • b7cf2d84...: 2365 αναφορές
     • green space strategies: 2166 αναφορές
     • 351122a2...: 2121 αναφορές
  ► [LIGNITE JOBS] (Σύνολο αναφορών: 243280)
     • 6cb9c23b...: 8371 αναφορές
     • d88cb3f1...: 6741 αναφορές
     • c5bc42be...: 5010 αναφορές
     • 3e40c7d0...: 4681 αναφορές
     • f4a6e9f7...: 3144 αναφορές

📍 ΧΩΡΑ: GREECE
  ► [GREEN JOBS] (Σύνολο αναφορών: 26383)
     • climatology: 476 αναφορές
     • 4b406514...: 475 αναφορές
     • f683ae1d...: 474 αναφορές
     • 15d76317...: 387 αναφορές
     • 199f7919...: 324 αναφορές
  ► [LIGNITE JOBS] (Σύνολο αναφορών: 18168)
     • c5bc42be...: 405 αναφορές
     • 6d3edede...: 362 αναφορές
     • 199f7919...: 309 αναφορές
     • f4a6e9f7...: 306 αναφορές
     • f683ae1d...: 296 αναφορές

📍 ΧΩΡΑ: ITALY
  ► [GREEN JOBS] (Σύνολο αναφορών: 1381)
     • efb523d0...: 143 αναφορές
     • 199f7919...: 56 αναφορές
     • 2fb8480e...: 54 αναφορές
     • urban sustainability: 54 αναφορές
     • 6f8baa62...: 54 αναφορές
  ► [LIGNITE JOBS] (Σύνολο αναφορών: 4240)
     • efb523d0...: 414 αναφορές
     • 6f8baa62...: 306 αναφορές
     • 199f7919...: 304 αναφορές
     • 2fb8480e...: 304 αναφορές
     • urban sustainability: 303 αναφορές

📍 ΧΩΡΑ: POLAND
  ► [GREEN JOBS] (Σύνολο αναφορών: 1323)
     • 113b4428...: 33 αναφορές
     • implement environmental protection measures: 27 αναφορές
     • f683ae1d...: 22 αναφορές
     • design ventilation network: 21 αναφορές
     • 199f7919...: 21 αναφορές
  ► [LIGNITE JOBS] (Σύνολο αναφορών: 815)
     • 113b4428...: 24 αναφορές
     • ef6cb992...: 23 αναφορές
     • d5e39a53...: 22 αναφορές
     • 978a76ca...: 19 αναφορές
     • 59ea80e1...: 18 αναφορές

📍 ΧΩΡΑ: ROMANIA
  ► [GREEN JOBS] (Σύνολο αναφορών: 122)
     • design a building management system: 41 αναφορές
     • social entreprise: 18 αναφορές
     • disinfect surfaces: 3 αναφορές
     • design ventilation network: 2 αναφορές
     • c662be22...: 2 αναφορές
  ► [LIGNITE JOBS] (Σύνολο αναφορών: 0)
     Δεν βρέθηκαν skills.

📍 ΧΩΡΑ: SPAIN
  ► [GREEN JOBS] (Σύνολο αναφορών: 1323)
     • ecopedagogy: 24 αναφορές
     • urban sustainability: 23 αναφορές
     • develop waste management processes: 22 αναφορές
     • disinfect surfaces: 19 αναφορές
     • c5bc42be...: 19 αναφορές
  ► [LIGNITE JOBS] (Σύνολο αναφορών: 1057)
     • c5bc42be...: 50 αναφορές
     • e0ded9a1...: 35 αναφορές
     • c4fe78ae...: 29 αναφορές
     • bf419e00...: 26 αναφορές
     • 2bbdea06...: 26 αναφορές

📍 ΧΩΡΑ: SWEDEN
  ► [GREEN JOBS] (Σύνολο αναφορών: 0)
     Δεν βρέθηκαν skills.
  ► [LIGNITE JOBS] (Σύνολο αναφορών: 190611)
     • 7ee51257...: 5344 αναφορές
     • 65715f7a...: 4793 αναφορές
     • 0da516ee...: 2762 αναφορές
     • 082967d4...: 2536 αναφορές
     • f4a6e9f7...: 2533 αναφορές

================================================================================
 2. TOP-5 ΔΕΞΙΟΤΗΤΕΣ ΕΡΓΑΖΟΜΕΝΩΝ ΑΝΑ ΧΩΡΑ (PROFILES)
================================================================================

--- Fill-rate πεδίου 'skills' στα profiles (πόσο αξιόπιστο είναι το top-5) ---

   category  country  total  with_skills  fill_rate_%
0     green  czechia   3064          328         10.7
1     green   france  54369         3433          6.3
2     green  germany  34557         3216          9.3
3     green   greece   4913         1073         21.8
4     green    italy  37320         3428          9.2
5     green   poland   8744         1119         12.8
6     green  romania   7997          937         11.7
7     green    spain  27707         3215         11.6
8     green   sweden  10136         1174         11.6
9   lignite  czechia   3036          352         11.6
10  lignite   france  45233         2389          5.3
11  lignite  germany  25707         2520          9.8
12  lignite   greece   3247          701         21.6
13  lignite    italy  23290         2065          8.9
14  lignite   poland   8731         1033         11.8
15  lignite  romania   5157          708         13.7
16  lignite    spain  21843         2023          9.3
17  lignite   sweden   9100         1037         11.4

📍 ΧΩΡΑ: CZECHIA
  ► [GREEN PROFILES] (Σύνολο αναφορών: 1007)
     • cd5efa8c...: 21 αναφορές
     • 15d76317...: 13 αναφορές
     • bda0d115...: 12 αναφορές
     • urban sustainability: 11 αναφορές
     • 9531fe02...: 10 αναφορές
  ► [LIGNITE PROFILES] (Σύνολο αναφορών: 999)
     • cd5efa8c...: 18 αναφορές
     • ccd0a1d9...: 14 αναφορές
     • f4a6e9f7...: 12 αναφορές
     • f0de4973...: 11 αναφορές
     • 75b30aeb...: 10 αναφορές

📍 ΧΩΡΑ: FRANCE
  ► [GREEN PROFILES] (Σύνολο αναφορών: 8108)
     • cd5efa8c...: 170 αναφορές
     • 15d76317...: 101 αναφορές
     • 2fb8480e...: 97 αναφορές
     • 19a8293b...: 81 αναφορές
     • ccd0a1d9...: 76 αναφορές
  ► [LIGNITE PROFILES] (Σύνολο αναφορών: 6106)
     • cd5efa8c...: 108 αναφορές
     • 2fb8480e...: 93 αναφορές
     • ccd0a1d9...: 81 αναφορές
     • 15d76317...: 69 αναφορές
     • c5bc42be...: 59 αναφορές

📍 ΧΩΡΑ: GERMANY
  ► [GREEN PROFILES] (Σύνολο αναφορών: 9257)
     • cd5efa8c...: 212 αναφορές
     • urban sustainability: 135 αναφορές
     • 2fb8480e...: 118 αναφορές
     • ccd0a1d9...: 79 αναφορές
     • 9531fe02...: 78 αναφορές
  ► [LIGNITE PROFILES] (Σύνολο αναφορών: 7237)
     • cd5efa8c...: 121 αναφορές
     • ccd0a1d9...: 93 αναφορές
     • 2fb8480e...: 80 αναφορές
     • f4a6e9f7...: 58 αναφορές
     • c3a03c5a...: 57 αναφορές

📍 ΧΩΡΑ: GREECE
  ► [GREEN PROFILES] (Σύνολο αναφορών: 3157)
     • cd5efa8c...: 60 αναφορές
     • urban sustainability: 48 αναφορές
     • a2b5dcf3...: 39 αναφορές
     • 7f18039d...: 33 αναφορές
     • fc4fcb4b...: 33 αναφορές
  ► [LIGNITE PROFILES] (Σύνολο αναφορών: 1973)
     • cd5efa8c...: 23 αναφορές
     • f4a6e9f7...: 23 αναφορές
     • 15d76317...: 23 αναφορές
     • urban sustainability: 17 αναφορές
     • ccd0a1d9...: 16 αναφορές

📍 ΧΩΡΑ: ITALY
  ► [GREEN PROFILES] (Σύνολο αναφορών: 9453)
     • cd5efa8c...: 205 αναφορές
     • urban sustainability: 117 αναφορές
     • 14ced458...: 117 αναφορές
     • 2fb8480e...: 106 αναφορές
     • 97965983...: 106 αναφορές
  ► [LIGNITE PROFILES] (Σύνολο αναφορών: 5985)
     • cd5efa8c...: 121 αναφορές
     • 2fb8480e...: 74 αναφορές
     • b633eb55...: 51 αναφορές
     • ccd0a1d9...: 40 αναφορές
     • f4a6e9f7...: 40 αναφορές

📍 ΧΩΡΑ: POLAND
  ► [GREEN PROFILES] (Σύνολο αναφορών: 3262)
     • cd5efa8c...: 60 αναφορές
     • 19a8293b...: 40 αναφορές
     • ccd0a1d9...: 32 αναφορές
     • f0de4973...: 29 αναφορές
     • 598de5b0...: 29 αναφορές
  ► [LIGNITE PROFILES] (Σύνολο αναφορών: 3080)
     • cd5efa8c...: 45 αναφορές
     • ccd0a1d9...: 42 αναφορές
     • 75b30aeb...: 40 αναφορές
     • 2fb8480e...: 31 αναφορές
     • 15d76317...: 29 αναφορές

📍 ΧΩΡΑ: ROMANIA
  ► [GREEN PROFILES] (Σύνολο αναφορών: 2578)
     • cd5efa8c...: 59 αναφορές
     • 15d76317...: 30 αναφορές
     • fc4fcb4b...: 29 αναφορές
     • 14ced458...: 29 αναφορές
     • 450de541...: 27 αναφορές
  ► [LIGNITE PROFILES] (Σύνολο αναφορών: 1928)
     • cd5efa8c...: 33 αναφορές
     • 15d76317...: 30 αναφορές
     • cf310cff...: 25 αναφορές
     • c5bc42be...: 22 αναφορές
     • ccd0a1d9...: 21 αναφορές

📍 ΧΩΡΑ: SPAIN
  ► [GREEN PROFILES] (Σύνολο αναφορών: 8429)
     • cd5efa8c...: 176 αναφορές
     • 9fc400ac...: 170 αναφορές
     • 89ff28d6...: 104 αναφορές
     • urban sustainability: 98 αναφορές
     • 2fb8480e...: 96 αναφορές
  ► [LIGNITE PROFILES] (Σύνολο αναφορών: 5867)
     • cd5efa8c...: 79 αναφορές
     • 2fb8480e...: 74 αναφορές
     • 9fc400ac...: 71 αναφορές
     • ccd0a1d9...: 67 αναφορές
     • c3a03c5a...: 51 αναφορές

📍 ΧΩΡΑ: SWEDEN
  ► [GREEN PROFILES] (Σύνολο αναφορών: 3599)
     • cd5efa8c...: 97 αναφορές
     • urban sustainability: 63 αναφορές
     • dba46f87...: 39 αναφορές
     • 15d76317...: 39 αναφορές
     • 75d8e5d9...: 37 αναφορές
  ► [LIGNITE PROFILES] (Σύνολο αναφορών: 2996)
     • cd5efa8c...: 81 αναφορές
     • 63f224ea...: 45 αναφορές
     • 15d76317...: 37 αναφορές
     • 2fb8480e...: 35 αναφορές
     • 75d8e5d9...: 32 αναφορές

================================================================================
 3. TOP-5 ΠΙΟ ΣΥΧΝΑ ΕΠΑΓΓΕΛΜΑΤΑ ΣΤΙΣ ΑΓΓΕΛΙΕΣ (JOBS)
================================================================================

📍 ΧΩΡΑ: CZECHIA
  ► [GREEN JOBS]
     • solid waste operator: 11 αγγελίες
     • 898f99f7-8c0a-4212-9e58-9ab00379e5ae: 7 αγγελίες
     • 1822bfc2-e735-449f-ba00-ca71eb5c062b: 7 αγγελίες
     • 044d78cc-f62f-4532-83a5-8e04f2889652: 6 αγγελίες
     • 1b8c75a9-407b-4554-a7d6-df391672c6b1: 6 αγγελίες
  ► [LIGNITE JOBS]
     • industrial machinery mechanic: 84 αγγελίες
     • bathroom fitter: 25 αγγελίες
     • land-based machinery technician: 25 αγγελίες
     • electricity distribution technician: 25 αγγελίες
     • electronics engineer: 18 αγγελίες

📍 ΧΩΡΑ: FRANCE
  ► [GREEN JOBS]
     • mobility services manager: 5236 αγγελίες
     • construction general contractor: 4229 αγγελίες
     • heating, ventilation, air conditioning and refrigeration engineering technician: 3206 αγγελίες
     • architect: 2558 αγγελίες
     • bea99fea-0383-4c63-b944-70d4799de2c5: 2482 αγγελίες
  ► [LIGNITE JOBS]
     • industrial machinery mechanic: 6836 αγγελίες
     • building electrician: 4362 αγγελίες
     • construction equipment technician: 3097 αγγελίες
     • electrical engineer: 2424 αγγελίες
     • chief data officer: 2393 αγγελίες

📍 ΧΩΡΑ: GERMANY
  ► [GREEN JOBS]
     • civil engineer: 7388 αγγελίες
     • landscape gardener: 3809 αγγελίες
     • horticulture worker: 2902 αγγελίες
     • garden labourer: 2275 αγγελίες
     • architect: 2002 αγγελίες
  ► [LIGNITE JOBS]
     • industrial machinery mechanic: 20805 αγγελίες
     • industrial electrician: 13518 αγγελίες
     • electrical engineer: 6037 αγγελίες
     • 1a6d1acf-5956-4ba0-95bf-b15b05a02013: 4137 αγγελίες
     • 691ec040-f5ad-47ef-8698-03212d66dbbf: 2377 αγγελίες

📍 ΧΩΡΑ: GREECE
  ► [GREEN JOBS]
     • 6cd08cbe-7611-4d70-8886-6c59c0385442: 571 αγγελίες
     • climatologist: 487 αγγελίες
     • environmental expert: 477 αγγελίες
     • emergency response coordinator: 297 αγγελίες
     • civil engineer: 296 αγγελίες
  ► [LIGNITE JOBS]
     • electrical engineer: 995 αγγελίες
     • industrial electrician: 534 αγγελίες
     • 6cd08cbe-7611-4d70-8886-6c59c0385442: 396 αγγελίες
     • electronics engineer: 309 αγγελίες
     • automation engineer: 237 αγγελίες

📍 ΧΩΡΑ: ITALY
  ► [GREEN JOBS]
     • solar energy sales consultant: 92 αγγελίες
     • e01719f4-d7dd-42fe-b504-93128520f84a: 92 αγγελίες
     • 21af40bb-2ae3-4fc7-9b28-d2cdd8308912: 92 αγγελίες
     • 509f9452-ed18-4fbf-8a4c-d45de85aa2f7: 22 αγγελίες
     • 21cba86a-68c5-456c-aec2-cc04840b3c0e: 22 αγγελίες
  ► [LIGNITE JOBS]
     • street lighting electrician: 190 αγγελίες
     • overhead line worker: 190 αγγελίες
     • cable jointer: 190 αγγελίες
     • industrial machinery mechanic: 160 αγγελίες
     • forestry machinery technician: 84 αγγελίες

📍 ΧΩΡΑ: POLAND
  ► [GREEN JOBS]
     • renewable energy sales representative: 50 αγγελίες
     • water network operative: 50 αγγελίες
     • civil engineer: 36 αγγελίες
     • insulation worker: 31 αγγελίες
     • construction general contractor: 25 αγγελίες
  ► [LIGNITE JOBS]
     • excavator operator: 102 αγγελίες
     • industrial machinery mechanic: 82 αγγελίες
     • bathroom fitter: 39 αγγελίες
     • industrial electrician: 27 αγγελίες
     • grinding machine operator: 20 αγγελίες

📍 ΧΩΡΑ: ROMANIA
  ► [GREEN JOBS]
     • 6c3fd65e-2d24-47d8-bc22-9e93512bdcc2: 1 αγγελίες
     • 2eac08c2-a81a-46fc-8d75-eb0e0f3e0f6d: 1 αγγελίες
  ► [LIGNITE JOBS]
     Δεν βρέθηκαν occupations.

📍 ΧΩΡΑ: SPAIN
  ► [GREEN JOBS]
     • landscape gardener: 94 αγγελίες
     • garden labourer: 53 αγγελίες
     • forest worker: 50 αγγελίες
     • environmental technician: 43 αγγελίες
     • civil engineer: 40 αγγελίες
  ► [LIGNITE JOBS]
     • occupational driving instructor: 328 αγγελίες
     • industrial machinery mechanic: 222 αγγελίες
     • greaser: 92 αγγελίες
     • excavator operator: 79 αγγελίες
     • building electrician: 48 αγγελίες

📍 ΧΩΡΑ: SWEDEN
  ► [GREEN JOBS]
     Δεν βρέθηκαν occupations.
  ► [LIGNITE JOBS]
     • electrical engineer: 6459 αγγελίες
     • 068370e0-9c27-4814-87d0-44fbb3140815: 6287 αγγελίες
     • electronics engineer: 3897 αγγελίες
     • bea99fea-0383-4c63-b944-70d4799de2c5: 3616 αγγελίες
     • automation engineer: 2302 αγγελίες

================================================================================
 4. ΣΥΓΚΡΙΣΗ ΚΛΑΔΩΝ (SECTORS): GREEN VS LIGNITE
================================================================================

📍 CZECHIA
  Κλάδοι που κυριαρχούν στο GREEN:
     • Other waste recovery: green=11 vs lignite=0
     • Landfilling or permanent storage: green=11 vs lignite=0
     • Collection of non-hazardous waste: green=11 vs lignite=0
     • Incineration without energy recovery: green=11 vs lignite=0
     • Machining of metals: green=10 vs lignite=0
  Κλάδοι που κυριαρχούν στο LIGNITE:
     • Repair and maintenance of machinery: lignite=109 vs green=0
     • Plumbing, heat and air-conditioning installation: lignite=42 vs green=3
     • Distribution of electricity: lignite=25 vs green=0
     • Engineering activities and related technical consultancy: lignite=33 vs green=9
     • Manufacture of instruments and appliances for measuring, testing and navigation: lignite=18 vs green=0

📍 FRANCE
  Κλάδοι που κυριαρχούν στο GREEN:
     • CONSTRUCTION: green=8673 vs lignite=897
     • Regulation of and contribution to more efficient operation of businesses: green=5896 vs lignite=128
     • General public administration activities: green=5959 vs lignite=312
     • Business and other management consultancy activities: green=7489 vs lignite=3230
     • Steam and air conditioning supply: green=4161 vs lignite=47
  Κλάδοι που κυριαρχούν στο LIGNITE:
     • Repair and maintenance of machinery: lignite=11642 vs green=51
     • Electrical installation: lignite=7215 vs green=58
     • Manufacture of electrical equipment: lignite=3459 vs green=630
     • Manufacture of electronic components: lignite=2655 vs green=289
     • Manufacture of other electronic and electric wires and cables: lignite=2040 vs green=0

📍 GERMANY
  Κλάδοι που κυριαρχούν στο GREEN:
     • CONSTRUCTION: green=7732 vs lignite=325
     • Landscape service activities: green=6244 vs lignite=0
     • Plant propagation: green=3390 vs lignite=2
     • Growing of perennial crops: green=3168 vs lignite=6
     • Growing of non-perennial crops: green=3168 vs lignite=6
  Κλάδοι που κυριαρχούν στο LIGNITE:
     • Repair and maintenance of machinery: lignite=22911 vs green=27
     • Electrical installation: lignite=14654 vs green=125
     • Manufacture of electrical equipment: lignite=7353 vs green=191
     • Manufacture of machinery and equipment n.e.c.: lignite=7138 vs green=271
     • Manufacture of electronic components: lignite=6467 vs green=252

📍 GREECE
  Κλάδοι που κυριαρχούν στο GREEN:
     • Research and experimental development on natural sciences and engineering: green=1299 vs lignite=190
     • Remediation activities and other waste management service activities: green=732 vs lignite=16
     • Business and other management consultancy activities: green=1085 vs lignite=437
     • Activities of head offices: green=1040 vs lignite=444
     • Regulation of health care, education, cultural services and other social services: green=506 vs lignite=24
  Κλάδοι που κυριαρχούν στο LIGNITE:
     • Manufacture of electrical equipment: lignite=1223 vs green=179
     • Manufacture of electronic components: lignite=1017 vs green=71
     • Electrical installation: lignite=738 vs green=10
     • Manufacture of other electrical equipment: lignite=370 vs green=13
     • Manufacture of electrical and electronic equipment for motor vehicles: lignite=370 vs green=13

📍 ITALY
  Κλάδοι που κυριαρχούν στο GREEN:
     • Wholesale of hardware, plumbing and heating equipment and supplies: green=92 vs lignite=0
     • Advertising: green=92 vs lignite=0
     • Activities of advertising agencies: green=92 vs lignite=0
     • Market research and public opinion polling: green=92 vs lignite=0
     • Other cleaning activities: green=46 vs lignite=0
  Κλάδοι που κυριαρχούν στο LIGNITE:
     • Distribution of electricity: lignite=191 vs green=0
     • Repair and maintenance of machinery: lignite=190 vs green=0
     • Transmission of electricity: lignite=190 vs green=0
     • Repair and maintenance of electrical equipment: lignite=87 vs green=0
     • Electrical installation: lignite=87 vs green=0

📍 POLAND
  Κλάδοι που κυριαρχούν στο GREEN:
     • Sewerage: green=65 vs lignite=1
     • CONSTRUCTION: green=61 vs lignite=2
     • Activities of brokers and agents for electric power and natural gas: green=50 vs lignite=0
     • Engineering activities and related technical consultancy: green=58 vs lignite=16
     • Installation of insulation: green=32 vs lignite=0
  Κλάδοι που κυριαρχούν στο LIGNITE:
     • Site preparation: lignite=128 vs green=0
     • Repair and maintenance of machinery: lignite=106 vs green=0
     • Electrical installation: lignite=31 vs green=2
     • Plumbing, heat and air-conditioning installation: lignite=39 vs green=14
     • Manufacture of power-driven hand tools: lignite=20 vs green=0

📍 ROMANIA
  Κλάδοι που κυριαρχούν στο GREEN:
     • Business and other management consultancy activities: green=1 vs lignite=0
     • Activities of head offices: green=1 vs lignite=0
  Κλάδοι που κυριαρχούν στο LIGNITE:
     • Activities of head offices: lignite=0 vs green=1
     • Business and other management consultancy activities: lignite=0 vs green=1

📍 SPAIN
  Κλάδοι που κυριαρχούν στο GREEN:
     • Landscape service activities: green=148 vs lignite=0
     • Silviculture and other forestry activities: green=128 vs lignite=0
     • Plant propagation: green=102 vs lignite=0
     • Growing of perennial crops: green=80 vs lignite=0
     • Engineering activities and related technical consultancy: green=123 vs lignite=43
  Κλάδοι που κυριαρχούν στο LIGNITE:
     • Repair and maintenance of machinery: lignite=349 vs green=0
     • Vocational secondary education: lignite=328 vs green=0
     • Electrical installation: lignite=91 vs green=4
     • Site preparation: lignite=79 vs green=0
     • Manufacture of electronic components: lignite=29 vs green=0

📍 SWEDEN
  Κλάδοι που κυριαρχούν στο GREEN:
     • Building of pleasure and sporting boats: green=0 vs lignite=1
     • Wholesale of live animals: green=0 vs lignite=1
     • Manufacture of knitted and crocheted fabrics: green=0 vs lignite=1
     • Manufacture of rusks, biscuits, preserved pastries and cakes: green=0 vs lignite=1
     • Wholesale of beverages: green=0 vs lignite=1
  Κλάδοι που κυριαρχούν στο LIGNITE:
     • Engineering activities and related technical consultancy: lignite=15030 vs green=0
     • Business and other management consultancy activities: lignite=10698 vs green=0
     • Manufacture of electrical equipment: lignite=8664 vs green=0
     • Technical testing and analysis: lignite=8397 vs green=0
     • Manufacture of electronic components: lignite=7110 vs green=0

================================================================================
 5. GREEN VS LIGNITE JOBS — ΛΟΓΟΣ & ΚΟΙΝΕΣ ΔΕΞΙΟΤΗΤΕΣ (ΓΕΦΥΡΕΣ)
================================================================================

,Country,Green Jobs,Lignite Jobs,Green/Lignite Ratio,Common Skills (count)
0,Czechia,371,237,1.57,80
1,France,40702,38154,1.07,3572
2,Germany,23789,48009,0.50,3469
3,Greece,3624,2887,1.26,1260
4,Italy,246,514,0.48,85
5,Poland,545,391,1.39,134
6,Romania,76,0,NaN,0
7,Spain,898,965,0.93,149
8,Sweden,0,24004,0.00,0

--- Ονόματα δεξιοτήτων-γεφυρών (κοινές lignite ↔ green jobs) ---

📍 CZECHIA — 80 κοινές δεξιότητες (top 10):
   • 001115fb...
   • 15d76317...
   • 0b3ee7c8...
   • 2d9aaad3...
   • 0f0698e7...
   • 00e895f4...
   • 50f5e41d...
   • 93a68dcb...
   • 5f95f9c9...
   • 7c632656...

📍 FRANCE — 3572 κοινές δεξιότητες (top 10):
   • 6b222aac...
   • 614fdb7f...
   • e1479957...
   • 2a0efd9a...
   • 3d96dc4c...
   • 26792722...
   • c7d8f44f...
   • 7ec3c77b...
   • f414dc08...
   • ec7ec825...

📍 GERMANY — 3469 κοινές δεξιότητες (top 10):
   • 50dd3681...
   • 614fdb7f...
   • e1479957...
   • 2a0efd9a...
   • ab580ada...
   • 62d34066...
   • daefc625...
   • 26514334...
   • 65df6a1d...
   • 1612575c...

📍 GREECE — 1260 κοινές δεξιότητες (top 10):
   • 614fdb7f...
   • 2a0efd9a...
   • db36f7f1...
   • a6d697d1...
   • f414dc08...
   • ec7ec825...
   • b4877620...
   • dfb9cec6...
   • f14ff4b7...
   • e5beeff8...

📍 ITALY — 85 κοινές δεξιότητες (top 10):
   • 6c153605...
   • b011c8b4...
   • 001115fb...
   • 51754b8a...
   • 63f224ea...
   • 92721092...
   • fe1ec582...
   • 50f5e41d...
   • d39022ab...
   • 9fd17276...

📍 POLAND — 134 κοινές δεξιότητες (top 10):
   • e1479957...
   • e3e42d54...
   • bda0d115...
   • 68698869...
   • bce2a9d6...
   • 15d76317...
   • 0b3ee7c8...
   • fc54bd7f...
   • cf310cff...
   • electric heating systems

📍 ROMANIA — 0 κοινές δεξιότητες (top 10):

📍 SPAIN — 149 κοινές δεξιότητες (top 10):
   • climatology
   • dispose of hazardous waste
   • 6c153605...
   • f3c5fae0...
   • 20a8fe89...
   • 048f04c9...
   • bda0d115...
   • 51754b8a...
   • 14ee9f76...
   • 1fcce318...

📍 SWEDEN — 0 κοινές δεξιότητες (top 10):

================================================================================
 6. SKILL MATCHING SCORE & GAP ANALYSIS (LIGNITE PROFILES VS GREEN JOBS)
================================================================================

--- Skill Matching Score (ετοιμότητα lignite → green) ---

,Country,Lignite Profile Skills,Green Job Skills Needed,Skill Matching Score (%)
1,France,1567,5175,88.39
2,Germany,1767,4782,72.95
3,Greece,894,2320,68.90
0,Czechia,531,569,23.16
5,Poland,1072,517,18.10
7,Spain,1583,586,16.93
4,Italy,1669,309,11.20
6,Romania,837,61,2.99
8,Sweden,1050,0,0.00

--- Top Skill Gaps ανά χώρα (μεγάλη ζήτηση, απούσα από lignite profiles) ---

📍 CZECHIA

   Country                         Missing Skill  Demand in Green Jobs
0  Czechia     operate water purifying equipment                    36
1  Czechia  manage water distribution procedures                    28
2  Czechia                promote animal welfare                    24
3  Czechia              manage health and safety                    21
4  Czechia            dispose of hazardous waste                    19
5  Czechia    develop waste management processes                    15
6  Czechia              dispose of sewage sludge                    14
7  Czechia            maintain sorting equipment                    13
8  Czechia                           0e21e183...                    12
9  Czechia                     social entreprise                    12

📍 FRANCE

  Country Missing Skill  Demand in Green Jobs
0  France   a6354281...                  1656
1  France   3e23db60...                   973
2  France   842d7168...                   844
3  France   6181f475...                   810
4  France   088dd17a...                   800
5  France   e24377fb...                   791
6  France   51e79cb4...                   566
7  France   de4bd326...                   553
8  France   ca49f512...                   458
9  France   e1479957...                   430

📍 GERMANY

   Country           Missing Skill  Demand in Green Jobs
0  Germany             8a1942a8...                  2404
1  Germany             b7cf2d84...                  2365
2  Germany  green space strategies                  2166
3  Germany             351122a2...                  2121
4  Germany             f4b4accf...                  2121
5  Germany             949fe489...                  2118
6  Germany             eadf0f36...                  1118
7  Germany             51097602...                  1074
8  Germany             af9b6098...                  1055
9  Germany             a472a200...                  1001

📍 GREECE

  Country Missing Skill  Demand in Green Jobs
0  Greece   climatology                   476
1  Greece   4b406514...                   475
2  Greece   6d3edede...                   240
3  Greece   bdcac0c8...                   137
4  Greece   68698869...                   128
5  Greece   e24377fb...                   104
6  Greece   0e21e183...                   103
7  Greece   e13b734a...                    97
8  Greece   6d97bf55...                    92
9  Greece   a15dab55...                    91

📍 ITALY

  Country          Missing Skill  Demand in Green Jobs
0   Italy            efb523d0...                   143
1   Italy  recirculation systems                    46
2   Italy            dbfb9dda...                    15
3   Italy            6d97bf55...                    11
4   Italy            fef5a450...                    10
5   Italy            c06b0686...                     9
6   Italy            5125b132...                     9
7   Italy            80e7418e...                     9
8   Italy            a2304e67...                     9
9   Italy            28c5e844...                     8

📍 POLAND

  Country                         Missing Skill  Demand in Green Jobs
0  Poland            design ventilation network                    21
1  Poland             environmental engineering                    16
2  Poland                           204713d1...                    16
3  Poland    develop waste management processes                    14
4  Poland                      spatial planning                    13
5  Poland             develop sewerage networks                    10
6  Poland     maintain waste collection records                    10
7  Poland                           811acf0c...                    10
8  Poland  manage water distribution procedures                    10
9  Poland                           6d97bf55...                    10

📍 ROMANIA

   Country                 Missing Skill  Demand in Green Jobs
0  Romania             social entreprise                    18
1  Romania            disinfect surfaces                     3
2  Romania    design ventilation network                     2
3  Romania                   c662be22...                     2
4  Romania        collect domestic waste                     1
5  Romania     sustainable manufacturing                     1
6  Romania                   8f6ed69b...                     1
7  Romania                   f206e732...                     1
8  Romania                  manage waste                     1
9  Romania  inspect industrial equipment                     1

📍 SPAIN

  Country                      Missing Skill  Demand in Green Jobs
0   Spain                 disinfect surfaces                    19
1   Spain                        e1479957...                    17
2   Spain      develop irrigation strategies                    16
3   Spain                        b7cf2d84...                    13
4   Spain                        5f95f9c9...                    13
5   Spain                        cb073ba6...                    11
6   Spain                        18a5e674...                    10
7   Spain  maintain waste collection records                     7
8   Spain                        5125b132...                     7
9   Spain                        aa43f245...                     7